# https://limeii.github.io/2022/11/deploy-on-multiple-environment-with-github-actions/
# https://blog.devgenius.io/deploying-multiple-environments-using-github-actions-ba063655ea55

name: Build and Deploy the application to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy the application'
        type: environment
        required: true

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: 20
  ARTIFACT_NAME: 'nextjs-deploy'
  S3_BUCKET: 'nextjs-deploy'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Zip artifact for deployment
        run: |
          cd out
          zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./out/release.zip

  dev_deploy:
    if: github.event_name == 'pull_request'
    name: Deploy to development environment
    runs-on: ubuntu-latest
    needs: build
    environment: "development"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Deploy to S3
      #   run: aws s3 sync ./out s3://${{ env.S3_BUCKET }}

  prod_deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy to production environment
    runs-on: ubuntu-latest
    needs: build
    environment: "production"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Deploy to S3
      #   run: aws s3 sync ./out s3://${{ env.S3_BUCKET }}
