# https://limeii.github.io/2022/11/deploy-on-multiple-environment-with-github-actions/
# https://blog.devgenius.io/deploying-multiple-environments-using-github-actions-ba063655ea55

name: Deploy application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy the application'
        type: environment
        required: true

env:
  ARTIFACT_NAME: 'nextjs-deploy'
  S3_BUCKET: 'nextjs-deploy'

jobs:
  deploy_dev:
    if: inputs.environment == 'development'
    runs-on: ubuntu-latest
    needs: build
    environment: "development"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}-dev

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          ls -la .

      - run: echo "My CHECK_ENV value is ${{ vars.CHECK_ENV }}"

      - run: echo "My BUCKET_NAME value is ${{ secrets.BUCKET_NAME }}"

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Deploy to S3
      #   run: aws s3 sync ./out s3://${{ env.S3_BUCKET }}

  deploy_prod:
    if: inputs.environment == 'production' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment: "production"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}-prod

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          ls -la .

      - run: echo "My CHECK_ENV value is ${{ vars.CHECK_ENV }}"

      - run: echo "My BUCKET_NAME value is ${{ secrets.BUCKET_NAME }}"

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Deploy to S3
      #   run: aws s3 sync ./out s3://${{ env.S3_BUCKET }}
